### ISSUE TITLE
[Feature Request] Assign a project to a new timer

### ISSUE THREAD

**Issue by BenJamesAndo** [bitfocus/companion-module-toggl-track#1]
So happy to see toggl in companion. Well done!
A feature I'd love to see added is the ability to assign a new timer with a selected project. Currently being able to assign a description is good, but also selecting a project would be great, providing the API allows for that.

**Comment by daniep01** [comment]
I have added this feature to a test build. Please download and let me know if it's working.

https://we.tl/t-3gf1EipI5k

Toggl put projects in workspaces, currently only the first workspace is checked for available projects.

**Comment by BenJamesAndo** [comment]
Thanks so much @daniep01 
I've tested it and it works great! It displayed all my projects.
I only use one workspace so that's fine.
