### ISSUE TITLE
[Feature Request] Button Feedback - Toggl Active

### ISSUE THREAD

**Issue by BenJamesAndo** [bitfocus/companion-module-toggl-track#2]
Hey, me again :)
This might be possible, but if not it'd be great to set feedback on a button to e.g. show red when a toggl timer is active, and then go black when it's no longer active.

**Comment by daniep01** [comment]
There's currently no background poll to see what's running on the toggl server but background colours can be easily changed by built in Companion commands.

**Comment by chabad360** [comment]
would it be possible to have an action that is refresh status and then I could use that in a trigger?

**Comment by daniep01** [comment]
How would this be different from the existing 'Get Current Timer' action?

**Comment by chabad360** [comment]
That action would be perfect if it would expose a variable (or something) to use for feedback, but right now it doesn't.

**Comment by daniep01** [comment]
I could easily put the timer id returned from toggl in a variable

**Comment by chabad360** [comment]
Do you think it could return some other metadata too (like name, time, description, etc.)?

**Comment by daniep01** [comment]
Variables for timerId and timerDescription have been added. Look out for a new beta with toggl-track 1.0.3

**Comment by chabad360** [comment]
Could we get current time also?

**Comment by daniep01** [comment]
Currently I can't see a way of getting the duration of a running timer from the toggl api.
