### ISSUE TITLE
Start new timer multiple presses issue

### ISSUE THREAD

**Issue by BenJamesAndo** [bitfocus/companion-module-toggl-track#3]
Hello. If I press the start new timer, it starts a new entry in Toggl. However, if I press the button again and again it'll stop the timer, then create another one and so on. So if I press the start new timer button 3 times, I'll end up with 3 entries.

The behaviour I'd expect is that if a timer is running that was initiated from Companion, and the start new timer button is pressed again, then nothing would happen, unless the description or Project is different to what it was the first time I pressed that same button.

But if how it's behaving is the intended way then all good. I'll just try not to press it multiple times by accident.

**Comment by daniep01** [comment]
Have you tried setting the button mode to latch?

The Latch/Toggle checkbox changes the push behavior of the button, making the first press of the button trigger all the Press/on actions, and a second press of the button trigger the Release/off actions.

**Comment by daniep01** [comment]
I have added a new module config option to fix this. By default it will not longer start a timer if one is already running.

**Comment by BenJamesAndo** [comment]
Hey sorry for my delay in replying. That was a good idea about latch/toggle mode. But I'm also really pleased you added a config option. I've tested it out today and it works great. Thanks so much!
