### ISSUE TITLE
Companion V3 compatibility

### ISSUE THREAD

**Issue by BenJamesAndo** [bitfocus/companion-module-toggl-track#4]
Hey, just wondering if there are plans to make this compatible with version 3?
I can confirm it's currently not working.

`23.06.23 09:16:54 Instance/Wrapper/toggl: Error getting config fields: Call timed out
23.06.23 09:16:54 Instance/Wrapper/toggl: Child is not running, unable to send message: {"direction":"call","name":"variablesChanged","payload":"{\"variablesIds\":[\"internal:time_hms\",\"internal:time_s\",\"internal:time_unix\"]}"}
23.06.23 09:16:55 Instance/Wrapper/toggl: Error getting config fields: Call timed out
23.06.23 09:16:56 Instance/ModuleHost: Registered module client "xxxxyyyyzzzz"
23.06.23 09:16:56 Instance/Controller: instance "toggl" configuration updated`

**Comment by daniep01** [comment]
Hi Ben, yes I am aware of this problem and will work on this soon.

**Comment by daniep01** [comment]
Please consider a donation to speed up development of v3 compatibility.

[https://github.com/sponsors/daniep01](https://github.com/sponsors/daniep01)

**Comment by daniep01** [comment]
Hi, here is a test release of the new v2 module.

[pkg.tgz](https://github.com/bitfocus/companion-module-toggl-track/files/11905127/pkg.tgz)

**Comment by BenJamesAndo** [comment]
Tested and works perfectly. Thanks so much!

**Comment by daniep01** [comment]
Here's a test build of the new v2 module which can be added to your Companion installation

[pkg.tgz](https://github.com/bitfocus/companion-module-toggl-track/files/11905479/pkg.tgz)

**Comment by BenJamesAndo** [comment]
I dunno if I'm doing something wrong, but with the new beta builds that include toggl, I can't get the module to show up. I search for it and it's simply not there. Tested on 2 Windows machines and on docker. I've checked and toggl files are in the 'bundled-modules' folder. Even using it via the Developer modules path doesn't work anymore. It might be a compile issue. Is it best to raise a bug report in the main companion Github?

**Comment by daniep01** [comment]
I have the same result, I've asked the companion devs if they know why

**Comment by daniep01** [comment]
I've found out why this was happening and it should be resolved in the next merge of modules

**Comment by daniep01** [comment]
Fixed in build 3.0.0+6010 and later
